# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f09f791ca97977a11121f68ada845748d67ba378b163edb3266496f4b4dc21563972cb5e05f0cc56ea77686f5ff5f8f0db4b9c0ab20ac85c37f8f6c6e441a35

test:
  secret_key_base: fffb19a2e9fa2a862e6f730ebe890a801a77681ecd60a417811aa2df14a42abe1ece7673cd6187ca03558bae6063cc9824a74933c951c4500b72471cacb91e78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
